export type {
  PlayerCoreState,
  SummonerClass,
  PlayerIdentity,
  SummonerProfile,
  SkillEntry,
  TalentNode,
  TitleEntry,
  AchievementEntry,
  PlayerStatistics,
  PlayerPrimaryStats,
  PlayerSecondaryStats,
  ReputationState,
  EquipmentSlot,
  EquipmentSlotId,
  CreatureContract,
  CreatureSlotType,
  CreatureSlotGroup,
  CreatureSlots,
  HousingReference,
  WorldUnlocks,
  SaveMetadata,
} from '../../types/playerCore.ts';
export { createDefaultPlayerCoreState, migratePlayerStateToCore, ARCHETYPE_TO_CLASS } from './factory.ts';
export { createCharacter, CONTRACT_PATHS } from './characterCreation.ts';
export type {
  ContractPath,
  ContractPathDefinition,
  CharacterCreationOptions,
  CharacterCreationResult,
} from './characterCreation.ts';
export {
  SUMMONER_CLASSES,
  getAllClasses,
  getClassById,
  getClassModifiers,
} from '../../data/summonerClasses';
export type { SummonerClassId, ClassDefinition } from '../../data/summonerClasses';
export { calculatePrimaryStats, calculateSecondaryStats, recalculateAllStats, getPrimaryStatsOrDefault, useFinalStats } from './playerStatistics';
export {
  getElementIdentity,
  getStarterElements,
  getQuestOnlyElements,
  getWorld100Element,
  isStarterElement,
  isQuestOnlyElement,
  getElementModifiers,
  getElementSkillDamagePct,
  getElementCreatureAffinityPct,
  getElementContractStabilityPct,
  getElementEquipmentScalingPct,
  getElementCraftingSuccessPct,
  getElementDungeonRewardPct,
  getElementNPCReactionPct,
  getElementWorldTravelSpeedPct,
  getElementPVPIdentityModifier,
} from '../../data/playerElements';
export type {
  ElementIdentity,
  ElementIdentityModifiers,
  StarterElement,
  QuestOnlyElement,
} from '../../data/playerElements';
export {
  getElementCombatBonuses,
  getElementAffinityBonuses,
  getElementCraftingBonuses,
  applyElementSkillDamageBoost,
  applyElementAffinityBoost,
  applyElementContractStabilityBoost,
  applyElementCraftingBoost,
  canObtainElement,
  getElementCategory,
} from './elementIdentity';
export {
  CREATURE_SLOT_TYPES,
  BASE_SLOT_COUNTS,
  createDefaultCreatureSlots,
  createEmptyCreatureSlots,
  getSlotGroup,
  getAvailableSlots,
  isSlotFull,
  getTotalMaxSlots,
  getUsedSlotCount,
  assignCreatureToSlot,
  removeCreatureFromSlot,
  moveCreatureBetweenSlots,
  getAssignedCreatures,
  expandSlots,
  expandAllSlots,
  calculateSlotExpansionFromLevel,
  calculateSlotExpansionFromEquipment,
  calculateSlotExpansionFromHousing,
  getFullSlotExpansion,
} from './creatureSlotCore';
export {
  getItemCategory,
  getItemRarity,
  canStackItems,
  stackItem,
  addItemToInventory,
  removeItemFromInventory,
  hasItem,
  getItemCount,
  sortInventory,
  filterInventory,
  getInventoryByCategory,
  canTradeItem,
  bindItem,
  getInventoryCapacity,
  isInventoryFull,
  getUniqueItemCount,
  getTotalItemCount,
  serializeInventory,
  deserializeInventory,
  migrateLegacyInventory,
  getDefaultInventory,
  createStartingInventory,
  mergeInventories,
  splitStack,
  clearInventory,
  pruneInvalidItems,
  ITEM_CATEGORY_TEMPLATES,
  RARITY_ORDER,
} from './inventoryCore';
export type {
  ItemCategory,
  ItemBinding,
  ItemRarity,
  InventorySortKey,
  InventorySortOrder,
  InventoryFilter,
  InventoryItem,
} from '../../types/playerCore.ts';
export {
  EQUIPMENT_SLOT_IDS,
  createEmptyEquipmentSlots,
  equipItem,
  unequipItem,
  getEquippedItem,
  getEquipmentBonuses,
  getSummoningCostModifier,
  getTravelUtilityModifier,
  isSlotOccupied,
  getFilledSlotCount,
  getEmptySlotCount,
} from './equipmentCore';

