export type {
  PlayerCoreState,
  SummonerClass,
  PlayerIdentity,
  SummonerProfile,
  SkillEntry,
  PlayerSkillCategory,
  PlayerSkillCategoryId,
  TalentTreeCategory,
  TalentTreeCategoryId,
  TalentNode,
  PlayerAchievementCategoryId,
  TitleEntry,
  AchievementEntry,
  PlayerStatistics,
  ReputationChange,
  ReputationChangeSource,
  ReputationDomain,
  ReputationEffects,
  PlayerPrimaryStats,
  PlayerSecondaryStats,
  ReputationState,
  EquipmentSlot,
  EquipmentSlotId,
  CreatureContract,
  CreatureSlotType,
  CreatureSlotGroup,
  CreatureSlots,
  HousingReference,
  WorldUnlocks,
  SaveMetadata,
} from '../../types/playerCore.ts';
export {
  PLAYER_SKILL_CATEGORIES,
  TALENT_TREE_CATEGORIES,
  getAllPlayerSkillCategories,
  getAllTalentTreeCategories,
  isPlayerSkillCategory,
  isTalentTreeCategory,
  inferSkillCategory,
  inferTalentCategory,
  normalizeSkillEntry,
  normalizeTalentNode,
  createSkillEntry,
  createTalentNode,
} from './skillTalentCore.ts';
export {
  TITLE_DEFINITIONS,
  ACHIEVEMENT_DEFINITIONS,
  getAllTitleDefinitions,
  getAllAchievementDefinitions,
  isPlayerAchievementCategory,
  normalizeTitleEntry,
  normalizeAchievementEntry,
  createTitleEntry,
  createAchievementEntry,
  evaluateAchievementProgress,
  evaluateAchievements,
  getUnlockedTitlesForAchievements,
  refreshTitleAchievementState,
} from './titleAchievementCore.ts';
export type { TitleDefinition, AchievementDefinition } from './titleAchievementCore.ts';
export { createDefaultPlayerCoreState, migratePlayerStateToCore, ARCHETYPE_TO_CLASS } from './factory.ts';
export { createCharacter, CONTRACT_PATHS } from './characterCreation.ts';
export type {
  ContractPath,
  ContractPathDefinition,
  CharacterCreationOptions,
  CharacterCreationResult,
} from './characterCreation.ts';
export {
  SUMMONER_CLASSES,
  getAllClasses,
  getClassById,
  getClassModifiers,
} from '../../data/summonerClasses';
export type { SummonerClassId, ClassDefinition } from '../../data/summonerClasses';
export { calculatePrimaryStats, calculateSecondaryStats, recalculateAllStats, getPrimaryStatsOrDefault, useFinalStats } from './playerStatistics';
export {
  REPUTATION_MAX,
  REPUTATION_MIN,
  REPUTATION_NEUTRAL,
  REPUTATION_SOURCE_MULTIPLIERS,
  applyPlayerReputationChange,
  applyReputationChange,
  calculateReputationEffects,
  createDefaultReputationState,
  getReputationScore,
} from './reputationCore';
export {
  PLAYER_STATISTIC_DEFINITIONS,
  createDefaultPlayerStatistics,
  normalizePlayerStatistics,
  mergePlayerStatistics,
  updatePlayerStatistic,
  applyPlayerStatisticEvent,
} from './playerStatisticsTracking';
export type {
  PlayerStatisticKey,
  PlayerStatisticUpdateMode,
  PlayerStatisticDefinition,
  PlayerStatisticEvent,
} from './playerStatisticsTracking';
export {
  getElementIdentity,
  getStarterElements,
  getQuestOnlyElements,
  getWorld100Element,
  isStarterElement,
  isQuestOnlyElement,
  getElementModifiers,
  getElementSkillDamagePct,
  getElementCreatureAffinityPct,
  getElementContractStabilityPct,
  getElementEquipmentScalingPct,
  getElementCraftingSuccessPct,
  getElementDungeonRewardPct,
  getElementNPCReactionPct,
  getElementWorldTravelSpeedPct,
  getElementPVPIdentityModifier,
} from '../../data/playerElements';
export type {
  ElementIdentity,
  ElementIdentityModifiers,
  StarterElement,
  QuestOnlyElement,
} from '../../data/playerElements';
export {
  getElementCombatBonuses,
  getElementAffinityBonuses,
  getElementCraftingBonuses,
  applyElementSkillDamageBoost,
  applyElementAffinityBoost,
  applyElementContractStabilityBoost,
  applyElementCraftingBoost,
  canObtainElement,
  getElementCategory,
} from './elementIdentity';
export {
  CREATURE_SLOT_TYPES,
  BASE_SLOT_COUNTS,
  createDefaultCreatureSlots,
  createEmptyCreatureSlots,
  getSlotGroup,
  getAvailableSlots,
  isSlotFull,
  getTotalMaxSlots,
  getUsedSlotCount,
  assignCreatureToSlot,
  removeCreatureFromSlot,
  moveCreatureBetweenSlots,
  getAssignedCreatures,
  expandSlots,
  expandAllSlots,
  calculateSlotExpansionFromLevel,
  calculateSlotExpansionFromEquipment,
  calculateSlotExpansionFromHousing,
  getFullSlotExpansion,
} from './creatureSlotCore';
export {
  createContract,
  validateContract,
  getContractById,
  hasContract,
  modifyBondLevel,
  adjustTrust,
  adjustLoyalty,
  updateContractStability,
  setTradeStatus,
  addCommandPermission,
  removeCommandPermission,
  grantBreedingRights,
  revokeBreedingRights,
  setPvpEligibility,
  calculateElementCompatibility,
  canTradeContract,
  canBreedContract,
  canPvPContract,
  serializeContract,
  deserializeContract,
  getContractSummary,
  DEFAULT_BOND_LEVEL,
  DEFAULT_TRUST,
  DEFAULT_LOYALTY,
  DEFAULT_CONTRACT_STABILITY,
  DEFAULT_ELEMENT_COMPATIBILITY,
  DEFAULT_COMMAND_PERMISSIONS,
  DEFAULT_TRADE_STATUS,
  DEFAULT_BREEDING_RIGHTS,
  DEFAULT_PVP_ELIGIBILITY,
  CONTRACT_STAT_MIN,
  CONTRACT_STAT_MAX,
  BOND_LEVEL_MAX,
  COMMAND_PERMISSIONS,
} from './contractCore';
export type { ContractValidationResult, ContractSummary } from './contractCore';
export {
  getItemCategory,
  getItemRarity,
  canStackItems,
  stackItem,
  addItemToInventory,
  removeItemFromInventory,
  hasItem,
  getItemCount,
  sortInventory,
  filterInventory,
  getInventoryByCategory,
  canTradeItem,
  bindItem,
  getInventoryCapacity,
  isInventoryFull,
  getUniqueItemCount,
  getTotalItemCount,
  serializeInventory,
  deserializeInventory,
  migrateLegacyInventory,
  getDefaultInventory,
  createStartingInventory,
  mergeInventories,
  splitStack,
  clearInventory,
  pruneInvalidItems,
  ITEM_CATEGORY_TEMPLATES,
  RARITY_ORDER,
} from './inventoryCore';
export type {
  ItemCategory,
  ItemBinding,
  ItemRarity,
  InventorySortKey,
  InventorySortOrder,
  InventoryFilter,
  InventoryItem,
} from '../../types/playerCore.ts';
export {
  EQUIPMENT_SLOT_IDS,
  createEmptyEquipmentSlots,
  equipItem,
  unequipItem,
  getEquippedItem,
  getEquipmentBonuses,
  getSummoningCostModifier,
  getTravelUtilityModifier,
  isSlotOccupied,
  getFilledSlotCount,
  getEmptySlotCount,
} from './equipmentCore';
export {
  hasCommandPermission,
  validateCommand,
  checkCommandEligibility,
  resolveCommandWithAI,
  getAvailableCommands,
  createDefaultCommandPermissions,
} from './commandCore';
export type {
  CreatureCommand,
  CommandContext,
  CommandValidationResult,
  CommandResolutionResult,
  CommandEffects,
} from './commandCore';
export {
  calculateSummonManaCost,
  getSummonCooldown,
  canSummonAtLocation,
  getSummonRestrictions,
  checkSummonEligibility,
  performSummon,
  isOnCooldown,
  getRemainingCooldown,
  getAffectionSummonBoost,
  calculateElementCompatibilityBoost,
  getSummonSuccessModifiers,
  getSummonSuccessChance,
  updateContractSummonedTime,
  clearContractSummonedTime,
  serializeSummonHistory,
  deserializeSummonHistory,
  BASE_SUMMON_MANA_COST,
  BASE_SUMMON_COOLDOWN_MS,
} from './summoningCore';
export type {
  SummonLocationType,
  SummonCheckResult,
  SummonResult,
  SummonState,
  SummonSuccessModifiers,
  SummonHistoryEntry,
} from './summoningCore';

